pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"

denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_guider_path: "./pretrained_weights/pose_guider.pth"

# denoising_unet_path: "./exp_output/stage1/denoising_unet-29920.pth"
# reference_unet_path: "./exp_output/stage1/reference_unet-29920.pth"
# pose_guider_path: "./exp_output/stage1/pose_guider-29920.pth"


motion_module_path: "./pretrained_weights/motion_module.pth"

# motion_module_path: "./pretrained_weights/motion_module-300.pth"
# motion_module_path: "./pretrained_weights/mm_sd_v15_v2.ckpt"
# motion_module_path: "./pretrained_weights/motion_module-9954.pth"

# motion_module_path: "./exp_output/finetune_stage2_cherry/motion_module-1495.pth"
# denoising_unet_path: "./exp_output/stage1_finetune1_cherry/denoising_unet-9960.pth"
# reference_unet_path: "./exp_output/stage1_finetune1_cherry/reference_unet-9960.pth"
# pose_guider_path: "./exp_output/stage1_finetune1_cherry/pose_guider-9960.pth"



inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:



  "/home/jgkwak/Moore-AnimateAnyone/Moore-AnimateAnyone/configs/inference/ref_images/1.png":
    - "/home/jgkwak/Moore-AnimateAnyone/oompa_cropped_dwpose/0006.mp4"
    - "/home/jgkwak/Moore-AnimateAnyone/oompa_cropped_dwpose/0002.mp4"
    - "/home/jgkwak/Moore-AnimateAnyone/oompa_cropped_dwpose/0011.mp4"

